services:
  prefect-server:
    build: ./data_pipeline/
    ports:
      - "4200:4200"
    env_file: .env
    environment:
      - DATABASE_URL
      - NEWS_API_KEY
      - PREFECT_API_URL=http://localhost:4200/api
    volumes:
      - ./data_pipeline:/app
      - prefect_data:/root/.prefect
    working_dir: /app
    command: prefect server start --host 0.0.0.0

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  celery-worker:
      build: ./data_pipeline/
      env_file: .env
      depends_on:
        - rabbitmq
        - postgres
      volumes:
        - ./data_pipeline:/app
      working_dir: /app
      command: celery -A celery_app worker --loglevel=info
      restart: always

  flower:
    build: ./data_pipeline/
    ports:
      - "5555:5555" 
    env_file: .env
    depends_on:
      - celery-worker
      - rabbitmq
    working_dir: /app 
    volumes:
      - ./data_pipeline:/app
    command: celery -A celery_app flower --address=0.0.0.0 --port=5555 --basic_auth=admin:adminpass
    restart: always

volumes:
  rabbitmq_data:
  prefect_data:
