"""Removed redundant 'source_name' and 'article_url' from reddit_posts

Revision ID: 0760ed71f445
Revises: 79c98c387ae9
Create Date: 2025-10-28 17:47:49.049368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0760ed71f445'
down_revision: Union[str, Sequence[str], None] = '79c98c387ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reddit_posts_article_url'), table_name='reddit_posts')
    op.drop_column('reddit_posts', 'article_url')
    op.drop_column('reddit_posts', 'source_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_posts', sa.Column('source_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment="The publisher's name (e.g., 'The Verge')."))
    op.add_column('reddit_posts', sa.Column('article_url', sa.TEXT(), autoincrement=False, nullable=True, comment='The URL that the post links to. If the post is a text post this is just the reddit post URL.'))
    op.create_index(op.f('ix_reddit_posts_article_url'), 'reddit_posts', ['article_url'], unique=False)
    # ### end Alembic commands ###
