"""Increase author column to 500 characters

Revision ID: 18bb12ac9627
Revises: 
Create Date: 2025-10-28 10:55:35.195554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bb12ac9627'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.alter_column('reddit_posts', 'article_headline',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_comment='The fetched article headline, if is_text_post is false')
    op.alter_column('reddit_posts', 'article_author',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='The fetched article author, if is_text_post is false')
    op.alter_column('reddit_posts', 'article_publisher',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='The fetched article publisher, if is_text_post is false')
    op.alter_column('reddit_posts', 'article_content',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='The fetched article content, if is_text_post is false')
    op.alter_column('reddit_posts', 'article_headline_cleaned',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_comment='The cleaned article headline (lowercased, noise-removed).')
    op.alter_column('reddit_posts', 'article_content_cleaned',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='The cleaned article content text (lowercased, noise-removed).')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reddit_posts', 'article_content_cleaned',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='The cleaned article content text (lowercased, noise-removed).')
    op.alter_column('reddit_posts', 'article_headline_cleaned',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_comment='The cleaned article headline (lowercased, noise-removed).')
    op.alter_column('reddit_posts', 'article_content',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='The fetched article content, if is_text_post is false')
    op.alter_column('reddit_posts', 'article_publisher',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='The fetched article publisher, if is_text_post is false')
    op.alter_column('reddit_posts', 'article_author',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='The fetched article author, if is_text_post is false')
    op.alter_column('reddit_posts', 'article_headline',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_comment='The fetched article headline, if is_text_post is false')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    # ### end Alembic commands ###
