"""Increase author column on the article table to 500 characters.

Revision ID: 5e4ae4a1e6e8
Revises: 18bb12ac9627
Create Date: 2025-10-28 10:59:37.916496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4ae4a1e6e8'
down_revision: Union[str, Sequence[str], None] = '18bb12ac9627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'author',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_comment="The article author (set to 'No Author' if missing).",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'author',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_comment="The article author (set to 'No Author' if missing).",
               existing_nullable=True)
    # ### end Alembic commands ###
