"""Make sentiment column in the articles table nullable

Revision ID: 72dff12e69d7
Revises: cfab4ab3c120
Create Date: 2025-10-29 09:44:30.262880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dff12e69d7'
down_revision: Union[str, Sequence[str], None] = 'cfab4ab3c120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'sentiment_strategy',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='The category tag used to segment the data.')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'sentiment_strategy',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='The category tag used to segment the data.')
    # ### end Alembic commands ###
