"""Add relationship between articles and reddit_posts entities, and removed the 'article_' columns from reddit_posts

Revision ID: 79c98c387ae9
Revises: 5e4ae4a1e6e8
Create Date: 2025-10-28 17:44:30.236028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79c98c387ae9'
down_revision: Union[str, Sequence[str], None] = '5e4ae4a1e6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_posts', 'article_content_cleaned')
    op.drop_column('reddit_posts', 'article_headline_cleaned')
    op.drop_column('reddit_posts', 'article_publisher')
    op.drop_column('reddit_posts', 'article_published_at')
    op.drop_column('reddit_posts', 'article_headline')
    op.drop_column('reddit_posts', 'article_author')
    op.drop_column('reddit_posts', 'article_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_posts', sa.Column('article_content', sa.TEXT(), autoincrement=False, nullable=True, comment='The fetched article content, if is_text_post is false'))
    op.add_column('reddit_posts', sa.Column('article_author', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='The fetched article author, if is_text_post is false'))
    op.add_column('reddit_posts', sa.Column('article_headline', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='The fetched article headline, if is_text_post is false'))
    op.add_column('reddit_posts', sa.Column('article_published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='The fetched article published date, if is_text_post is false'))
    op.add_column('reddit_posts', sa.Column('article_publisher', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='The fetched article publisher, if is_text_post is false'))
    op.add_column('reddit_posts', sa.Column('article_headline_cleaned', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='The cleaned article headline (lowercased, noise-removed).'))
    op.add_column('reddit_posts', sa.Column('article_content_cleaned', sa.TEXT(), autoincrement=False, nullable=True, comment='The cleaned article content text (lowercased, noise-removed).'))
    # ### end Alembic commands ###
