"""empty message

Revision ID: ba95bd6af949
Revises: e26643b1dbdd
Create Date: 2025-11-07 13:29:25.881126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba95bd6af949'
down_revision: Union[str, Sequence[str], None] = 'e26643b1dbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'sentiment_strategy',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_comment='The category tag used to segment the data.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'sentiment_strategy',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_comment='The category tag used to segment the data.',
               existing_nullable=True)
    # ### end Alembic commands ###
