"""empty message

Revision ID: e26643b1dbdd
Revises: 72dff12e69d7
Create Date: 2025-11-06 20:45:39.071499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26643b1dbdd'
down_revision: Union[str, Sequence[str], None] = '72dff12e69d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'sentiment_strategy',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_comment='The category tag used to segment the data.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'sentiment_strategy',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_comment='The category tag used to segment the data.',
               existing_nullable=True)
    # ### end Alembic commands ###
